
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Configuration
{

    public int ConfigurationId { get; set; }

    public Nullable<decimal> ExchangeRate { get; set; }

    public int AdminAcceptanceBalancePercentage { get; set; }

    public int ClientAcceptanceBalancePercentage { get; set; }

}

}
