
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class EmailTemplate
{

    public int EmailTemplateID { get; set; }

    public int ApplicationID { get; set; }

    public string Placed { get; set; }

    public string Cancelled { get; set; }

    public string Updated { get; set; }

    public string PartialApproval { get; set; }

    public string NotApproved { get; set; }

    public string Approved { get; set; }

    public string IntoReviewOnPlaced { get; set; }

    public string Done { get; set; }

    public string Paid { get; set; }

}

}
