
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ModuleAction
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ModuleAction()
    {

        this.RoleModuleActions = new HashSet<RoleModuleAction>();

    }


    public int ModuleActionID { get; set; }

    public string Module { get; set; }

    public string Action { get; set; }

    public string Description { get; set; }

    public Nullable<int> OrderIndex { get; set; }

    public Nullable<int> Group { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoleModuleAction> RoleModuleActions { get; set; }

}

}
