
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Question()
    {

        this.Answers = new HashSet<Answer>();

        this.Choices = new HashSet<Choice>();

        this.UserTestQuestions = new HashSet<UserTestQuestion>();

    }


    public int QuestionID { get; set; }

    public string QuestionText { get; set; }

    public Nullable<int> QuizID { get; set; }

    public string AudioUrl { get; set; }

    public string Title { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public bool Status { get; set; }

    public string Description { get; set; }

    public Nullable<double> Point { get; set; }

    public Nullable<int> Type { get; set; }

    public Nullable<int> ContestID { get; set; }

    public Nullable<int> SectionID { get; set; }

    public Nullable<int> Order { get; set; }

    public Nullable<int> Layout { get; set; }

    public Nullable<int> TimeLimit { get; set; }

    public string ImageUrl { get; set; }

    public Nullable<int> MaxLengthText { get; set; }

    public Nullable<bool> StatusTextbox { get; set; }

    public Nullable<int> GroupIndex { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Answer> Answers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Choice> Choices { get; set; }

    public virtual Contest Contest { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual Section Section { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserTestQuestion> UserTestQuestions { get; set; }

}

}
