
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Role
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {

        this.RoleModuleActions = new HashSet<RoleModuleAction>();

        this.UserRoles = new HashSet<UserRole>();

    }


    public int RoleId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

    public bool Status { get; set; }

    public Nullable<int> Type { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string CreatedByUserId { get; set; }

    public string UpdatedUserId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoleModuleAction> RoleModuleActions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRoles { get; set; }

}

}
