
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Section
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Section()
    {

        this.Questions = new HashSet<Question>();

        this.UserTestQuestions = new HashSet<UserTestQuestion>();

    }


    public int SectionID { get; set; }

    public string SectionName { get; set; }

    public string Title { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public int Status { get; set; }

    public string Description { get; set; }

    public Nullable<int> Type { get; set; }

    public Nullable<int> Order { get; set; }

    public Nullable<int> QuizID { get; set; }

    public Nullable<int> ContestID { get; set; }

    public string TimeLimit { get; set; }

    public Nullable<int> OrderIndex { get; set; }



    public virtual Contest Contest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Question> Questions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserTestQuestion> UserTestQuestions { get; set; }

}

}
