
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tms.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.UserRoles = new HashSet<UserRole>();

        this.UserTests = new HashSet<UserTest>();

    }


    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PasswordSalt { get; set; }

    public bool IsSupperAdmin { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<System.DateTime> LastLoginDate { get; set; }

    public Nullable<System.DateTime> LastActivityDate { get; set; }

    public bool IsLockedOut { get; set; }

    public string Avatar { get; set; }

    public bool Status { get; set; }

    public string FullName { get; set; }

    public string Tel { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<int> Gender { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    public string Address { get; set; }

    public string IdentityCardNo { get; set; }

    public string PhoneNo { get; set; }

    public string ChineseName { get; set; }

    public Nullable<int> Level { get; set; }

    public string CountryCode { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRoles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserTest> UserTests { get; set; }

}

}
